# Generated by Django 3.1.6 on 2021-06-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='Name',
            new_name='Movie Title',
        ),
    ]
