# Generated by Django 3.1.6 on 2021-06-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210602_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='Movie Title',
            new_name='title',
        ),
    ]
