# Generated by Django 3.1.6 on 2021-06-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210602_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Movie Title'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year_of_release',
            field=models.IntegerField(null=True, verbose_name='Year of Release'),
        ),
    ]
