# Generated by Django 3.1.6 on 2021-06-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_inventory_product_purchase_purchaseline_sales_salesline_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product',
        ),
    ]
